# Generated by Django 3.2.16 on 2023-02-09 11:24

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(blank=True, default=bookings.models.create_booking_ref, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
